export enum SocketNotification {
  INIT = 'INIT',
  POST_INIT = 'POST_INIT',

  // Collaborators
  FETCH_COLLABORATORS = 'FETCH_COLLABORATORS',
  HANDLE_COLLABORATORS = 'HANDLE_COLLABORATORS',
  // Labels
  FETCH_LABELS = 'FETCH_LABELS',
  HANDLE_LABELS = 'HANDLE_LABELS',
  // Projects
  FETCH_PROJECTS = 'FETCH_PROJECTS',
  HANDLE_PROJECTS = 'HANDLE_PROJECTS',
  // Tasks
  FETCH_TASKS = 'FETCH_TASKS',
  HANDLE_TASKS = 'HANDLE_TASKS',
}
